function cleanWeaponStats(weaponsObj) {
    const cleanedWeapons = {};
  
    for (const [weapon, stats] of Object.entries(weaponsObj)) {
      cleanedWeapons[weapon] = {};
  
      for (const [stat, value] of Object.entries(stats)) {
        let cleanedValue = value;
  
        if (stat === "Rate of Fire") {
          cleanedValue = value.replace("rpm", "");
        } else if (stat === "Reload Speed" || stat === "Cycle Time") {
          cleanedValue = value.replace("s", "");
        } else if (stat === "Effective Range") {
          cleanedValue = value.replace("m", "");
        }else if (stat === "Cycle Time") {
          cleanedValue = value.replace("m", "");
        }else if (stat === "Muzzle Velocity") {
          cleanedValue = value.replace("m/s", "");
        }
  
        cleanedWeapons[weapon][stat] = cleanedValue;
      }
    }
  
    return cleanedWeapons;
  }
  let a = {
    "Nagant M1895": {
      "Capacity": "7/21",
      "Damage": "91",
      "Cycle Time": "15s",
      "Vertical Recoil": "4",
      "Melee Damage": "13",
      "Effective Range": "74m",
      "Spread": "40",
      "Reload Speed": "125s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "2lrpm",
      "Sway": "128",
      "Muzzle Velocity": "330m/s",
      "Stamina Consumption": "20",
      "Price": "24"
    },
    "Hand Crossbow": {
      "Capacity": "1/16",
      "Damage": "195",
      "Cycle Time": "45s",
      "Vertical Recoil": "12",
      "Melee Damage": "13",
      "Effective Range": "12m",
      "Spread": "25",
      "Reload Speed": "43s",
      "Heavy Melee Damage": "27",
      "Rate of Fire": "14rpm",
      "Sway": "82",
      "Muzzle Velocity": "100m/s",
      "Stamina Consumption": "10",
      "Price": "30"
    },
    "Caldwell Conversion Pistol": {
      "Capacity": "6/18",
      "Damage": "104",
      "Cycle Time": "14s",
      "Vertical Recoil": "45",
      "Melee Damage": "13",
      "Effective Range": "85m",
      "Spread": "30",
      "Reload Speed": "112s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "2lrpm",
      "Sway": "128",
      "Muzzle Velocity": "300m/s",
      "Stamina Consumption": "20",
      "Price": ") 55"
    },
    "Scottfield Model 3": {
      "Capacity": "6/12",
      "Damage": "107",
      "Cycle Time": "15s",
      "Vertical Recoil": "9",
      "Melee Damage": "13",
      "Effective Range": "85m",
      "Spread": "28.1",
      "Reload Speed": "9s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "24rpm",
      "Sway": "128",
      "Muzzle Velocity": "280m/s",
      "Stamina Consumption": "20",
      "Price": "77"
    },
    "Caldwell Pax": {
      "Capacity": "6/12.",
      "Damage": "110",
      "Cycle Time": "14s",
      "Vertical Recoil": "10",
      "Melee Damage": "13",
      "Effective Range": "87m",
      "Spread": "325",
      "Reload Speed": "112s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "22rpm",
      "Sway": "128",
      "Muzzle Velocity": "330m/s",
      "Stamina Consumption": "20",
      "Price": "80"
    },
    "LeMat Mark II": {
      "Capacity": "9/18",
      "Damage": "97",
      "Cycle Time": "13s",
      "Vertical Recoil": "6",
      "Melee Damage": "13",
      "Effective Range": "80m",
      "Spread": "40",
      "Reload Speed": "15.85",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "25rpm",
      "Sway": "128",
      "Muzzle Velocity": "375m/s",
      "Stamina Consumption": "20",
      "Price": "| 83"
    },
    "Caldwell Conversion Chain Pistol": {
      "Capacity": "17/18",
      "Damage": "104",
      "Cycle Time": "14s",
      "Vertical Recoil": "35",
      "Melee Damage": "13",
      "Effective Range": "85m",
      "Spread": "45",
      "Reload Speed": "287s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "24rpm",
      "Sway": "128",
      "Muzzle Velocity": "300m/s",
      "Stamina Consumption": "20",
      "Price": "84"
    },
    "Scottfield Model 3 Brawler": {
      "Capacity": "6/12",
      "Damage": "107",
      "Cycle Time": "15s",
      "Vertical Recoil": "12",
      "Melee Damage": "31",
      "Effective Range": "85m",
      "Spread": "45",
      "Reload Speed": "9s",
      "Heavy Melee Damage": "72",
      "Rate of Fire": "24rpm",
      "Sway": "128",
      "Muzzle Velocity": "280m/s",
      "Stamina Consumption": "10",
      "Price": "87"
    },
    "Caldwell 92 New Army": {
      "Capacity": "6/12",
      "Damage": "97",
      "Cycle Time": "0.55",
      "Vertical Recoil": "5",
      "Melee Damage": "13",
      "Effective Range": "80m",
      "Spread": "475",
      "Reload Speed": "9.55",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "30rpm",
      "Sway": "128",
      "Muzzle Velocity": "230m/s",
      "Stamina Consumption": "20",
      "Price": "90"
    },
    "Caldwell Pax Claw": {
      "Capacity": "6/12",
      "Damage": "110",
      "Cycle Time": "14s",
      "Vertical Recoil": "10",
      "Melee Damage": "52",
      "Effective Range": "87m",
      "Spread": "325",
      "Reload Speed": "112s",
      "Heavy Melee Damage": "105",
      "Rate of Fire": "22rpm",
      "Sway": "128",
      "Muzzle Velocity": "330m/s",
      "Stamina Consumption": "25",
      "Price": "90"
    },
    "Nagant M1895 Silencer": {
      "Capacity": "7/21",
      "Damage": "91",
      "Cycle Time": "15s",
      "Vertical Recoil": "4",
      "Melee Damage": "13",
      "Effective Range": "57m",
      "Spread": "45",
      "Reload Speed": "125s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "2lrpm",
      "Sway": "128",
      "Muzzle Velocity": "250m/s",
      "Stamina Consumption": "20",
      "Price": "93"
    },
    "Scottfield Model 3 Swift": {
      "Capacity": "6/12",
      "Damage": "107",
      "Cycle Time": "15s",
      "Vertical Recoil": "9",
      "Melee Damage": "13",
      "Effective Range": "85m",
      "Spread": "28.1",
      "Reload Speed": "43s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "30rpm",
      "Sway": "128",
      "Muzzle Velocity": "280m/s",
      "Stamina Consumption": "20",
      "Price": "| 95"
    },
    "Nagant M1895 Officer": {
      "Capacity": "7/14",
      "Damage": "91",
      "Cycle Time": "0.55",
      "Vertical Recoil": "5",
      "Melee Damage": "13",
      "Effective Range": "74m",
      "Spread": "50",
      "Reload Speed": "128s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "28rpm",
      "Sway": "128",
      "Muzzle Velocity": "330m/s",
      "Stamina Consumption": "20",
      "Price": "96"
    },
    "Nagant M1895 Officer Brawler": {
      "Capacity": "7/14",
      "Damage": "91",
      "Cycle Time": "0.55",
      "Vertical Recoil": "5",
      "Melee Damage": "31",
      "Effective Range": "74m",
      "Spread": "50",
      "Reload Speed": "128s",
      "Heavy Melee Damage": "72",
      "Rate of Fire": "28rpm",
      "Sway": "128",
      "Muzzle Velocity": "330m/s",
      "Stamina Consumption": "10",
      "Price": "106"
    },
    "Caldwell 92 New Army Swift": {
      "Capacity": "6/12",
      "Damage": "97",
      "Cycle Time": "0.55",
      "Vertical Recoil": "5",
      "Melee Damage": "13",
      "Effective Range": "80m",
      "Spread": "475",
      "Reload Speed": "56s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "40rpm",
      "Sway": "128",
      "Muzzle Velocity": "230m/s",
      "Stamina Consumption": "20",
      "Price": "108"
    },
    "Scottfield Model 3 Spitfire": {
      "Capacity": "6/12",
      "Damage": "107",
      "Cycle Time": "0.8s",
      "Vertical Recoil": "12",
      "Melee Damage": "13",
      "Effective Range": "85m",
      "Spread": "45",
      "Reload Speed": "9s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "30rpm",
      "Sway": "128",
      "Muzzle Velocity": "280m/s",
      "Stamina Consumption": "20",
      "Price": "108"
    },
    "Caldwell Pax Trueshot": {
      "Capacity": "6/12",
      "Damage": "114",
      "Cycle Time": "1.6s",
      "Vertical Recoil": "16",
      "Melee Damage": "13",
      "Effective Range": "89m",
      "Spread": "275",
      "Reload Speed": "112s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "18rpm.",
      "Sway": "128",
      "Muzzle Velocity": "410m/s",
      "Stamina Consumption": "20",
      "Price": "141"
    },
    "Bornheim No. 3": {
      "Capacity": "5+1/15",
      "Damage": "74",
      "Cycle Time": "0.2s",
      "Vertical Recoil": "6",
      "Melee Damage": "13",
      "Effective Range": "62m",
      "Spread": "25",
      "Reload Speed": "74s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "65rpm",
      "Sway": "128",
      "Muzzle Velocity": "380m/s",
      "Stamina Consumption": "20",
      "Price": "146"
    },
    "Sparks Pistol": {
      "Capacity": "1/14",
      "Damage": "149",
      "Cycle Time": "509s",
      "Vertical Recoil": "25",
      "Melee Damage": "13",
      "Effective Range": "150m",
      "Spread": "425",
      "Reload Speed": "5s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "1lrpm",
      "Sway": "128",
      "Muzzle Velocity": "453m/s",
      "Stamina Consumption": "25",
      "Price": "155"
    },
    "Bornheim No. 3 Silencer": {
      "Capacity": "5+1/15",
      "Damage": "74",
      "Cycle Time": "0.2s",
      "Vertical Recoil": "6",
      "Melee Damage": "13",
      "Effective Range": "48m",
      "Spread": "25",
      "Reload Speed": "74s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "65rpm",
      "Sway": "128",
      "Muzzle Velocity": "300m/s",
      "Stamina Consumption": "20",
      "Price": "174"
    },
    "Bornheim No. 3 Extended": {
      "Capacity": "8+1/15",
      "Damage": "74",
      "Cycle Time": "0.2s",
      "Vertical Recoil": "6",
      "Melee Damage": "13",
      "Effective Range": "62m",
      "Spread": "25",
      "Reload Speed": "9.65",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "44rpm",
      "Sway": "128",
      "Muzzle Velocity": "380m/s",
      "Stamina Consumption": "20",
      "Price": "203"
    },
    "Caldwell Conversion Uppercut": {
      "Capacity": "6/9",
      "Damage": "126",
      "Cycle Time": "16s",
      "Vertical Recoil": "23",
      "Melee Damage": "13",
      "Effective Range": "115m",
      "Spread": "40",
      "Reload Speed": "16s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "18rpm.",
      "Sway": "128",
      "Muzzle Velocity": "410m/s",
      "Stamina Consumption": "20",
      "Price": "414"
    },
    "Dolch 96": {
      "Capacity": "10/10",
      "Damage": "97",
      "Cycle Time": "0.4s",
      "Vertical Recoil": "14",
      "Melee Damage": "13",
      "Effective Range": "78m",
      "Spread": "35",
      "Reload Speed": "6s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "64rpm",
      "Sway": "128",
      "Muzzle Velocity": "440m/s",
      "Stamina Consumption": "20",
      "Price": "690"
    },
    "Dolch 96 Claw": {
      "Capacity": "10/10",
      "Damage": "97",
      "Cycle Time": "0.4s",
      "Vertical Recoil": "14",
      "Melee Damage": "52",
      "Effective Range": "78m",
      "Spread": "35",
      "Reload Speed": "6s",
      "Heavy Melee Damage": "105",
      "Rate of Fire": "64rpm",
      "Sway": "128",
      "Muzzle Velocity": "440m/s",
      "Stamina Consumption": "25",
      "Price": "700"
    },
    "Dolch 96 Deadeye": {
      "Capacity": "10/10",
      "Damage": "97",
      "Cycle Time": "0.4s",
      "Vertical Recoil": "14",
      "Melee Damage": "13",
      "Effective Range": "78m",
      "Spread": "50",
      "Reload Speed": "217s",
      "Heavy Melee Damage": "31",
      "Rate of Fire": "40rpm",
      "Sway": "106",
      "Muzzle Velocity": "440m/s",
      "Stamina Consumption": "20",
      "Price": "780"
    }
  }
  cleanWeaponStats(a);